name: 'Continuous Integration'

on:
  pull_request:
    branches:
      - '2.x'
  push:
    branches:
      - '2.x'

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ github.job }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.job }}-npm-

      - name: List the state of dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm ci

      - name: Run all suites
        run: npm run all

  integration-test:
    name: Integration Test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ github.job }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.job }}-npm-

      - name: List the state of dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm ci

      - name: Always build latest distributable
        run: |
          npm run build
          npm run package

      - name: Run on PR
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
